;System Log monitor
;by immortalyzy
; Last update : 2019-02-28
; Created on  : 2019-02-27


;=========================================================================================================================

[Variables]

;-------------------------------------------------------------------------------------------------------------------------
; Logs to display
; Most interesting logs : Application , System
; TODO: Security log is also interesting, however Rainmeter will not have the access to the log
; 
; But you can specify additional logs by add the log name in the "Logs" variable, seperate by ", " (Note there is a space after ',' !!)
;
Logs=System,Application,Microsoft-Windows-Known Folders API Service,Security,Microsoft-Windows-Shell-Core/Operational


; color in RGBA
Color = 155,255,155,255

; 
